name: asthma
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - accelerate=1.2.1
  - anyio=4.8.0
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - arviz=0.20.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - atk-1.0=2.38.0
  - attrs=24.3.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - blas=2.126
  - blas-devel=3.9.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2024.12.14
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.0
  - cairo=1.18.2
  - cctools_osx-arm64=1010.6
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - clang=18.1.8
  - clang-18=18.1.8
  - clang_impl_osx-arm64=18.1.8
  - clang_osx-arm64=18.1.8
  - clangxx=18.1.8
  - clangxx_impl_osx-arm64=18.1.8
  - clangxx_osx-arm64=18.1.8
  - cloudpickle=3.1.0
  - colorama=0.4.6
  - comm=0.2.2
  - compiler-rt=18.1.8
  - compiler-rt_osx-arm64=18.1.8
  - cons=0.4.6
  - contourpy=1.3.1
  - cpython=3.11.11
  - cycler=0.12.1
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - et_xmlfile=2.0.0
  - etuples=0.3.9
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - filelock=3.16.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.3
  - fqdn=1.5.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - fsspec=2024.12.0
  - gdk-pixbuf=2.42.12
  - gmp=6.3.0
  - gmpy2=2.1.5
  - graphite2=1.3.13
  - graphviz=12.0.0
  - gtk2=2.24.33
  - gts=0.7.6
  - h11=0.14.0
  - h2=4.1.0
  - h5netcdf=1.4.1
  - h5py=3.12.1
  - harfbuzz=10.1.0
  - hdf5=1.14.4
  - hpack=4.0.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - huggingface_hub=0.27.1
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=8.31.0
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - json5=0.10.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.11.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - ld64_osx-arm64=951.9
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp18.1=18.1.8
  - libcurl=8.11.1
  - libcxx=19.1.6
  - libcxx-devel=18.1.8
  - libdeflate=1.23
  - libedit=3.1.20240808
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgd=2.3.3
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.82.2
  - libiconv=1.17
  - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm18=18.1.8
  - liblzma=5.6.3
  - libnghttp2=1.64.0
  - libopenblas=0.3.28
  - libpng=1.6.45
  - libprotobuf=5.28.3
  - librsvg=2.58.4
  - libsodium=1.0.20
  - libsqlite=3.47.2
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libuv=1.49.2
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.5
  - libzlib=1.3.1
  - llvm-openmp=19.1.6
  - llvm-tools=18.1.8
  - llvm-tools-18=18.1.8
  - logical-unification=0.4.6
  - macosx_deployment_target_osx-arm64=11.0
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - minikanren=1.0.3
  - mistune=3.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert-core=7.16.5
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nomkl=1.0
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - openblas=0.3.28
  - openjpeg=2.5.3
  - openpyxl=3.1.5
  - openssl=3.4.0
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - pango=1.54.0
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=24.3.1
  - pixman=0.44.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.48
  - psutil=6.1.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.1
  - pymc=5.20.0
  - pymc-base=5.20.0
  - pyobjc-core=10.3.2
  - pyobjc-framework-cocoa=10.3.2
  - pyparsing=3.2.1
  - pysocks=1.7.1
  - pytensor=2.26.4
  - pytensor-base=2.26.4
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-graphviz=0.20.3
  - python-json-logger=2.0.7
  - python-tzdata=2024.2
  - python_abi=3.11
  - pytorch=2.5.1
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - rpds-py=0.22.3
  - safetensors=0.5.2
  - scipy=1.15.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=75.6.0
  - sigtool=0.1.3
  - six=1.17.0
  - sleef=3.7
  - sniffio=1.3.1
  - soupsieve=2.5
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - sympy=1.13.3
  - tapi=1300.6.5
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - toolz=1.0.0
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024b
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.3.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - xarray=2025.1.0
  - xarray-einstats=0.8.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.6